/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Sensor Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getDescription <em>Description</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getType <em>Type</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getQuery <em>Query</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralSensorInfo()
 * @model
 * @generated
 */
public interface GeneralSensorInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralSensorInfo_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link it.unibo.sensor.dsl.sensorDSL.TYPES}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.TYPES
   * @see #setType(TYPES)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralSensorInfo_Type()
   * @model
   * @generated
   */
  TYPES getType();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.TYPES
   * @see #getType()
   * @generated
   */
  void setType(TYPES value);

  /**
   * Returns the value of the '<em><b>Query</b></em>' containment reference list.
   * The list contents are of type {@link it.unibo.sensor.dsl.sensorDSL.Query}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' containment reference list.
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralSensorInfo_Query()
   * @model containment="true"
   * @generated
   */
  EList<Query> getQuery();

} // GeneralSensorInfo
