/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Gateway Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getUrl <em>Url</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getRegister <em>Register</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getShutdown <em>Shutdown</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getDetection <em>Detection</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getAlert <em>Alert</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralGatewayInfo()
 * @model
 * @generated
 */
public interface GeneralGatewayInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralGatewayInfo_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Register</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Register</em>' attribute.
   * @see #setRegister(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralGatewayInfo_Register()
   * @model
   * @generated
   */
  String getRegister();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getRegister <em>Register</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Register</em>' attribute.
   * @see #getRegister()
   * @generated
   */
  void setRegister(String value);

  /**
   * Returns the value of the '<em><b>Shutdown</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shutdown</em>' attribute.
   * @see #setShutdown(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralGatewayInfo_Shutdown()
   * @model
   * @generated
   */
  String getShutdown();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getShutdown <em>Shutdown</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shutdown</em>' attribute.
   * @see #getShutdown()
   * @generated
   */
  void setShutdown(String value);

  /**
   * Returns the value of the '<em><b>Detection</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Detection</em>' attribute.
   * @see #setDetection(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralGatewayInfo_Detection()
   * @model
   * @generated
   */
  String getDetection();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getDetection <em>Detection</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Detection</em>' attribute.
   * @see #getDetection()
   * @generated
   */
  void setDetection(String value);

  /**
   * Returns the value of the '<em><b>Alert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alert</em>' attribute.
   * @see #setAlert(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralGatewayInfo_Alert()
   * @model
   * @generated
   */
  String getAlert();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getAlert <em>Alert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alert</em>' attribute.
   * @see #getAlert()
   * @generated
   */
  void setAlert(String value);

} // GeneralGatewayInfo
