/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Query#getName <em>Name</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Query#getComparator <em>Comparator</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Query#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getQuery_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Query#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Comparator</b></em>' attribute.
   * The literals are from the enumeration {@link it.unibo.sensor.dsl.sensorDSL.Comparator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparator</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.Comparator
   * @see #setComparator(Comparator)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getQuery_Comparator()
   * @model
   * @generated
   */
  Comparator getComparator();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Query#getComparator <em>Comparator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparator</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.Comparator
   * @see #getComparator()
   * @generated
   */
  void setComparator(Comparator value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getQuery_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Query#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Query
