/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.SensorDefinition#getSensor <em>Sensor</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensorDefinition()
 * @model
 * @generated
 */
public interface SensorDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' containment reference.
   * @see #setSensor(Sensor)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensorDefinition_Sensor()
   * @model containment="true"
   * @generated
   */
  Sensor getSensor();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.SensorDefinition#getSensor <em>Sensor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor</em>' containment reference.
   * @see #getSensor()
   * @generated
   */
  void setSensor(Sensor value);

} // SensorDefinition
