/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SensorDSLStandaloneSetup extends SensorDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new SensorDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
