/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Network Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getPort <em>Port</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getIp <em>Ip</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralNetworkInfo()
 * @model
 * @generated
 */
public interface GeneralNetworkInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralNetworkInfo_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' attribute.
   * @see #setIp(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralNetworkInfo_Ip()
   * @model
   * @generated
   */
  String getIp();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getIp <em>Ip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' attribute.
   * @see #getIp()
   * @generated
   */
  void setIp(String value);

} // GeneralNetworkInfo
