/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Cronjob Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getFrom <em>From</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getTo <em>To</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getDay <em>Day</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getType <em>Type</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getHour <em>Hour</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getMinute <em>Minute</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getValue <em>Value</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo()
 * @model
 * @generated
 */
public interface GeneralCronjobInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' attribute.
   * The literals are from the enumeration {@link it.unibo.sensor.dsl.sensorDSL.DAY}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see #setFrom(DAY)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_From()
   * @model
   * @generated
   */
  DAY getFrom();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getFrom <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see #getFrom()
   * @generated
   */
  void setFrom(DAY value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * The literals are from the enumeration {@link it.unibo.sensor.dsl.sensorDSL.DAY}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see #setTo(DAY)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_To()
   * @model
   * @generated
   */
  DAY getTo();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see #getTo()
   * @generated
   */
  void setTo(DAY value);

  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * The literals are from the enumeration {@link it.unibo.sensor.dsl.sensorDSL.DAY}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see #setDay(DAY)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_Day()
   * @model
   * @generated
   */
  DAY getDay();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see #getDay()
   * @generated
   */
  void setDay(DAY value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Hour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hour</em>' attribute.
   * @see #setHour(int)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_Hour()
   * @model
   * @generated
   */
  int getHour();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getHour <em>Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hour</em>' attribute.
   * @see #getHour()
   * @generated
   */
  void setHour(int value);

  /**
   * Returns the value of the '<em><b>Minute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minute</em>' attribute.
   * @see #setMinute(int)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_Minute()
   * @model
   * @generated
   */
  int getMinute();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getMinute <em>Minute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minute</em>' attribute.
   * @see #getMinute()
   * @generated
   */
  void setMinute(int value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getGeneralCronjobInfo_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

} // GeneralCronjobInfo
