/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage
 * @generated
 */
public interface SensorDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SensorDSLFactory eINSTANCE = it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Sensor Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Definition</em>'.
   * @generated
   */
  SensorDefinition createSensorDefinition();

  /**
   * Returns a new object of class '<em>Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor</em>'.
   * @generated
   */
  Sensor createSensor();

  /**
   * Returns a new object of class '<em>General Network Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>General Network Info</em>'.
   * @generated
   */
  GeneralNetworkInfo createGeneralNetworkInfo();

  /**
   * Returns a new object of class '<em>General Sensor Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>General Sensor Info</em>'.
   * @generated
   */
  GeneralSensorInfo createGeneralSensorInfo();

  /**
   * Returns a new object of class '<em>General Gateway Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>General Gateway Info</em>'.
   * @generated
   */
  GeneralGatewayInfo createGeneralGatewayInfo();

  /**
   * Returns a new object of class '<em>Sensor Registry Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Registry Info</em>'.
   * @generated
   */
  SensorRegistryInfo createSensorRegistryInfo();

  /**
   * Returns a new object of class '<em>General Cronjob Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>General Cronjob Info</em>'.
   * @generated
   */
  GeneralCronjobInfo createGeneralCronjobInfo();

  /**
   * Returns a new object of class '<em>Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query</em>'.
   * @generated
   */
  Query createQuery();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SensorDSLPackage getSensorDSLPackage();

} //SensorDSLFactory
