/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getName <em>Name</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getInfos <em>Infos</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getNetwork <em>Network</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getGateway <em>Gateway</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getRegistry <em>Registry</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getCronjob <em>Cronjob</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Infos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infos</em>' containment reference.
   * @see #setInfos(GeneralSensorInfo)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor_Infos()
   * @model containment="true"
   * @generated
   */
  GeneralSensorInfo getInfos();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getInfos <em>Infos</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Infos</em>' containment reference.
   * @see #getInfos()
   * @generated
   */
  void setInfos(GeneralSensorInfo value);

  /**
   * Returns the value of the '<em><b>Network</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Network</em>' containment reference.
   * @see #setNetwork(GeneralNetworkInfo)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor_Network()
   * @model containment="true"
   * @generated
   */
  GeneralNetworkInfo getNetwork();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getNetwork <em>Network</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Network</em>' containment reference.
   * @see #getNetwork()
   * @generated
   */
  void setNetwork(GeneralNetworkInfo value);

  /**
   * Returns the value of the '<em><b>Gateway</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gateway</em>' containment reference.
   * @see #setGateway(GeneralGatewayInfo)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor_Gateway()
   * @model containment="true"
   * @generated
   */
  GeneralGatewayInfo getGateway();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getGateway <em>Gateway</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gateway</em>' containment reference.
   * @see #getGateway()
   * @generated
   */
  void setGateway(GeneralGatewayInfo value);

  /**
   * Returns the value of the '<em><b>Registry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registry</em>' containment reference.
   * @see #setRegistry(SensorRegistryInfo)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor_Registry()
   * @model containment="true"
   * @generated
   */
  SensorRegistryInfo getRegistry();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getRegistry <em>Registry</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registry</em>' containment reference.
   * @see #getRegistry()
   * @generated
   */
  void setRegistry(SensorRegistryInfo value);

  /**
   * Returns the value of the '<em><b>Cronjob</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cronjob</em>' containment reference.
   * @see #setCronjob(GeneralCronjobInfo)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensor_Cronjob()
   * @model containment="true"
   * @generated
   */
  GeneralCronjobInfo getCronjob();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getCronjob <em>Cronjob</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cronjob</em>' containment reference.
   * @see #getCronjob()
   * @generated
   */
  void setCronjob(GeneralCronjobInfo value);

} // Sensor
