/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Registry Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getRegistryUrl <em>Registry Url</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getApiKey <em>Api Key</em>}</li>
 * </ul>
 *
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensorRegistryInfo()
 * @model
 * @generated
 */
public interface SensorRegistryInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>Registry Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registry Url</em>' attribute.
   * @see #setRegistryUrl(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensorRegistryInfo_RegistryUrl()
   * @model
   * @generated
   */
  String getRegistryUrl();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getRegistryUrl <em>Registry Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registry Url</em>' attribute.
   * @see #getRegistryUrl()
   * @generated
   */
  void setRegistryUrl(String value);

  /**
   * Returns the value of the '<em><b>Api Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Api Key</em>' attribute.
   * @see #setApiKey(String)
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getSensorRegistryInfo_ApiKey()
   * @model
   * @generated
   */
  String getApiKey();

  /**
   * Sets the value of the '{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getApiKey <em>Api Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Api Key</em>' attribute.
   * @see #getApiKey()
   * @generated
   */
  void setApiKey(String value);

} // SensorRegistryInfo
