/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLFactory
 * @model kind="package"
 * @generated
 */
public interface SensorDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sensorDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unibo.it/sensor/dsl/SensorDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sensorDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SensorDSLPackage eINSTANCE = it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.SensorDefinitionImpl <em>Sensor Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDefinitionImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getSensorDefinition()
   * @generated
   */
  int SENSOR_DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_DEFINITION__SENSOR = 0;

  /**
   * The number of structural features of the '<em>Sensor Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Infos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__INFOS = 1;

  /**
   * The feature id for the '<em><b>Network</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NETWORK = 2;

  /**
   * The feature id for the '<em><b>Gateway</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__GATEWAY = 3;

  /**
   * The feature id for the '<em><b>Registry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__REGISTRY = 4;

  /**
   * The feature id for the '<em><b>Cronjob</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__CRONJOB = 5;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralNetworkInfoImpl <em>General Network Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralNetworkInfoImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralNetworkInfo()
   * @generated
   */
  int GENERAL_NETWORK_INFO = 2;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_NETWORK_INFO__PORT = 0;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_NETWORK_INFO__IP = 1;

  /**
   * The number of structural features of the '<em>General Network Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_NETWORK_INFO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralSensorInfoImpl <em>General Sensor Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralSensorInfoImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralSensorInfo()
   * @generated
   */
  int GENERAL_SENSOR_INFO = 3;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_SENSOR_INFO__DESCRIPTION = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_SENSOR_INFO__TYPE = 1;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_SENSOR_INFO__QUERY = 2;

  /**
   * The number of structural features of the '<em>General Sensor Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_SENSOR_INFO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl <em>General Gateway Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralGatewayInfo()
   * @generated
   */
  int GENERAL_GATEWAY_INFO = 4;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO__URL = 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO__PORT = 1;

  /**
   * The feature id for the '<em><b>Register</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO__REGISTER = 2;

  /**
   * The feature id for the '<em><b>Shutdown</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO__SHUTDOWN = 3;

  /**
   * The feature id for the '<em><b>Detection</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO__DETECTION = 4;

  /**
   * The feature id for the '<em><b>Alert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO__ALERT = 5;

  /**
   * The number of structural features of the '<em>General Gateway Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_GATEWAY_INFO_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.SensorRegistryInfoImpl <em>Sensor Registry Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorRegistryInfoImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getSensorRegistryInfo()
   * @generated
   */
  int SENSOR_REGISTRY_INFO = 5;

  /**
   * The feature id for the '<em><b>Registry Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_REGISTRY_INFO__REGISTRY_URL = 0;

  /**
   * The feature id for the '<em><b>Api Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_REGISTRY_INFO__API_KEY = 1;

  /**
   * The number of structural features of the '<em>Sensor Registry Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_REGISTRY_INFO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralCronjobInfoImpl <em>General Cronjob Info</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralCronjobInfoImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralCronjobInfo()
   * @generated
   */
  int GENERAL_CRONJOB_INFO = 6;

  /**
   * The feature id for the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__FROM = 0;

  /**
   * The feature id for the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__TO = 1;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__DAY = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__TYPE = 3;

  /**
   * The feature id for the '<em><b>Hour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__HOUR = 4;

  /**
   * The feature id for the '<em><b>Minute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__MINUTE = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__VALUE = 6;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO__UNIT = 7;

  /**
   * The number of structural features of the '<em>General Cronjob Info</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CRONJOB_INFO_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.impl.QueryImpl
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__NAME = 0;

  /**
   * The feature id for the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__COMPARATOR = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__VALUE = 2;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.DAY <em>DAY</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getDAY()
   * @generated
   */
  int DAY = 8;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.Comparator <em>Comparator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.Comparator
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getComparator()
   * @generated
   */
  int COMPARATOR = 9;

  /**
   * The meta object id for the '{@link it.unibo.sensor.dsl.sensorDSL.TYPES <em>TYPES</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.unibo.sensor.dsl.sensorDSL.TYPES
   * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getTYPES()
   * @generated
   */
  int TYPES = 10;


  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.SensorDefinition <em>Sensor Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Definition</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDefinition
   * @generated
   */
  EClass getSensorDefinition();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.sensor.dsl.sensorDSL.SensorDefinition#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sensor</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.SensorDefinition#getSensor()
   * @see #getSensorDefinition()
   * @generated
   */
  EReference getSensorDefinition_Sensor();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getInfos <em>Infos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Infos</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor#getInfos()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Infos();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getNetwork <em>Network</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Network</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor#getNetwork()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Network();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getGateway <em>Gateway</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Gateway</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor#getGateway()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Gateway();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getRegistry <em>Registry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Registry</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor#getRegistry()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Registry();

  /**
   * Returns the meta object for the containment reference '{@link it.unibo.sensor.dsl.sensorDSL.Sensor#getCronjob <em>Cronjob</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cronjob</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Sensor#getCronjob()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Cronjob();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo <em>General Network Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Network Info</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo
   * @generated
   */
  EClass getGeneralNetworkInfo();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getPort()
   * @see #getGeneralNetworkInfo()
   * @generated
   */
  EAttribute getGeneralNetworkInfo_Port();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralNetworkInfo#getIp()
   * @see #getGeneralNetworkInfo()
   * @generated
   */
  EAttribute getGeneralNetworkInfo_Ip();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo <em>General Sensor Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Sensor Info</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo
   * @generated
   */
  EClass getGeneralSensorInfo();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getDescription()
   * @see #getGeneralSensorInfo()
   * @generated
   */
  EAttribute getGeneralSensorInfo_Description();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getType()
   * @see #getGeneralSensorInfo()
   * @generated
   */
  EAttribute getGeneralSensorInfo_Type();

  /**
   * Returns the meta object for the containment reference list '{@link it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Query</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralSensorInfo#getQuery()
   * @see #getGeneralSensorInfo()
   * @generated
   */
  EReference getGeneralSensorInfo_Query();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo <em>General Gateway Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Gateway Info</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo
   * @generated
   */
  EClass getGeneralGatewayInfo();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getUrl()
   * @see #getGeneralGatewayInfo()
   * @generated
   */
  EAttribute getGeneralGatewayInfo_Url();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getPort()
   * @see #getGeneralGatewayInfo()
   * @generated
   */
  EAttribute getGeneralGatewayInfo_Port();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getRegister <em>Register</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Register</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getRegister()
   * @see #getGeneralGatewayInfo()
   * @generated
   */
  EAttribute getGeneralGatewayInfo_Register();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getShutdown <em>Shutdown</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Shutdown</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getShutdown()
   * @see #getGeneralGatewayInfo()
   * @generated
   */
  EAttribute getGeneralGatewayInfo_Shutdown();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getDetection <em>Detection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Detection</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getDetection()
   * @see #getGeneralGatewayInfo()
   * @generated
   */
  EAttribute getGeneralGatewayInfo_Detection();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getAlert <em>Alert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alert</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo#getAlert()
   * @see #getGeneralGatewayInfo()
   * @generated
   */
  EAttribute getGeneralGatewayInfo_Alert();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo <em>Sensor Registry Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Registry Info</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo
   * @generated
   */
  EClass getSensorRegistryInfo();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getRegistryUrl <em>Registry Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Registry Url</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getRegistryUrl()
   * @see #getSensorRegistryInfo()
   * @generated
   */
  EAttribute getSensorRegistryInfo_RegistryUrl();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getApiKey <em>Api Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Api Key</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.SensorRegistryInfo#getApiKey()
   * @see #getSensorRegistryInfo()
   * @generated
   */
  EAttribute getSensorRegistryInfo_ApiKey();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo <em>General Cronjob Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Cronjob Info</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo
   * @generated
   */
  EClass getGeneralCronjobInfo();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>From</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getFrom()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_From();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getTo()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_To();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getDay()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_Day();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getType()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_Type();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getHour <em>Hour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hour</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getHour()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_Hour();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getMinute <em>Minute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minute</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getMinute()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_Minute();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getValue()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_Value();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.GeneralCronjobInfo#getUnit()
   * @see #getGeneralCronjobInfo()
   * @generated
   */
  EAttribute getGeneralCronjobInfo_Unit();

  /**
   * Returns the meta object for class '{@link it.unibo.sensor.dsl.sensorDSL.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.Query#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Query#getName()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Name();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.Query#getComparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparator</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Query#getComparator()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Comparator();

  /**
   * Returns the meta object for the attribute '{@link it.unibo.sensor.dsl.sensorDSL.Query#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Query#getValue()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Value();

  /**
   * Returns the meta object for enum '{@link it.unibo.sensor.dsl.sensorDSL.DAY <em>DAY</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>DAY</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.DAY
   * @generated
   */
  EEnum getDAY();

  /**
   * Returns the meta object for enum '{@link it.unibo.sensor.dsl.sensorDSL.Comparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparator</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.Comparator
   * @generated
   */
  EEnum getComparator();

  /**
   * Returns the meta object for enum '{@link it.unibo.sensor.dsl.sensorDSL.TYPES <em>TYPES</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>TYPES</em>'.
   * @see it.unibo.sensor.dsl.sensorDSL.TYPES
   * @generated
   */
  EEnum getTYPES();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SensorDSLFactory getSensorDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.SensorDefinitionImpl <em>Sensor Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDefinitionImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getSensorDefinition()
     * @generated
     */
    EClass SENSOR_DEFINITION = eINSTANCE.getSensorDefinition();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_DEFINITION__SENSOR = eINSTANCE.getSensorDefinition_Sensor();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '<em><b>Infos</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__INFOS = eINSTANCE.getSensor_Infos();

    /**
     * The meta object literal for the '<em><b>Network</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__NETWORK = eINSTANCE.getSensor_Network();

    /**
     * The meta object literal for the '<em><b>Gateway</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__GATEWAY = eINSTANCE.getSensor_Gateway();

    /**
     * The meta object literal for the '<em><b>Registry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__REGISTRY = eINSTANCE.getSensor_Registry();

    /**
     * The meta object literal for the '<em><b>Cronjob</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__CRONJOB = eINSTANCE.getSensor_Cronjob();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralNetworkInfoImpl <em>General Network Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralNetworkInfoImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralNetworkInfo()
     * @generated
     */
    EClass GENERAL_NETWORK_INFO = eINSTANCE.getGeneralNetworkInfo();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_NETWORK_INFO__PORT = eINSTANCE.getGeneralNetworkInfo_Port();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_NETWORK_INFO__IP = eINSTANCE.getGeneralNetworkInfo_Ip();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralSensorInfoImpl <em>General Sensor Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralSensorInfoImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralSensorInfo()
     * @generated
     */
    EClass GENERAL_SENSOR_INFO = eINSTANCE.getGeneralSensorInfo();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_SENSOR_INFO__DESCRIPTION = eINSTANCE.getGeneralSensorInfo_Description();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_SENSOR_INFO__TYPE = eINSTANCE.getGeneralSensorInfo_Type();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_SENSOR_INFO__QUERY = eINSTANCE.getGeneralSensorInfo_Query();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl <em>General Gateway Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralGatewayInfo()
     * @generated
     */
    EClass GENERAL_GATEWAY_INFO = eINSTANCE.getGeneralGatewayInfo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_GATEWAY_INFO__URL = eINSTANCE.getGeneralGatewayInfo_Url();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_GATEWAY_INFO__PORT = eINSTANCE.getGeneralGatewayInfo_Port();

    /**
     * The meta object literal for the '<em><b>Register</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_GATEWAY_INFO__REGISTER = eINSTANCE.getGeneralGatewayInfo_Register();

    /**
     * The meta object literal for the '<em><b>Shutdown</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_GATEWAY_INFO__SHUTDOWN = eINSTANCE.getGeneralGatewayInfo_Shutdown();

    /**
     * The meta object literal for the '<em><b>Detection</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_GATEWAY_INFO__DETECTION = eINSTANCE.getGeneralGatewayInfo_Detection();

    /**
     * The meta object literal for the '<em><b>Alert</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_GATEWAY_INFO__ALERT = eINSTANCE.getGeneralGatewayInfo_Alert();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.SensorRegistryInfoImpl <em>Sensor Registry Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorRegistryInfoImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getSensorRegistryInfo()
     * @generated
     */
    EClass SENSOR_REGISTRY_INFO = eINSTANCE.getSensorRegistryInfo();

    /**
     * The meta object literal for the '<em><b>Registry Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_REGISTRY_INFO__REGISTRY_URL = eINSTANCE.getSensorRegistryInfo_RegistryUrl();

    /**
     * The meta object literal for the '<em><b>Api Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_REGISTRY_INFO__API_KEY = eINSTANCE.getSensorRegistryInfo_ApiKey();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralCronjobInfoImpl <em>General Cronjob Info</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.GeneralCronjobInfoImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getGeneralCronjobInfo()
     * @generated
     */
    EClass GENERAL_CRONJOB_INFO = eINSTANCE.getGeneralCronjobInfo();

    /**
     * The meta object literal for the '<em><b>From</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__FROM = eINSTANCE.getGeneralCronjobInfo_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__TO = eINSTANCE.getGeneralCronjobInfo_To();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__DAY = eINSTANCE.getGeneralCronjobInfo_Day();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__TYPE = eINSTANCE.getGeneralCronjobInfo_Type();

    /**
     * The meta object literal for the '<em><b>Hour</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__HOUR = eINSTANCE.getGeneralCronjobInfo_Hour();

    /**
     * The meta object literal for the '<em><b>Minute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__MINUTE = eINSTANCE.getGeneralCronjobInfo_Minute();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__VALUE = eINSTANCE.getGeneralCronjobInfo_Value();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CRONJOB_INFO__UNIT = eINSTANCE.getGeneralCronjobInfo_Unit();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.impl.QueryImpl
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__NAME = eINSTANCE.getQuery_Name();

    /**
     * The meta object literal for the '<em><b>Comparator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__COMPARATOR = eINSTANCE.getQuery_Comparator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__VALUE = eINSTANCE.getQuery_Value();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.DAY <em>DAY</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.DAY
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getDAY()
     * @generated
     */
    EEnum DAY = eINSTANCE.getDAY();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.Comparator <em>Comparator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.Comparator
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getComparator()
     * @generated
     */
    EEnum COMPARATOR = eINSTANCE.getComparator();

    /**
     * The meta object literal for the '{@link it.unibo.sensor.dsl.sensorDSL.TYPES <em>TYPES</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.unibo.sensor.dsl.sensorDSL.TYPES
     * @see it.unibo.sensor.dsl.sensorDSL.impl.SensorDSLPackageImpl#getTYPES()
     * @generated
     */
    EEnum TYPES = eINSTANCE.getTYPES();

  }

} //SensorDSLPackage
