/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>TYPES</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage#getTYPES()
 * @model
 * @generated
 */
public enum TYPES implements Enumerator
{
  /**
   * The '<em><b>Hydro</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HYDRO_VALUE
   * @generated
   * @ordered
   */
  HYDRO(0, "hydro", "idro_level"),

  /**
   * The '<em><b>Temperature</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TEMPERATURE_VALUE
   * @generated
   * @ordered
   */
  TEMPERATURE(1, "temperature", "temp"),

  /**
   * The '<em><b>Humidity</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HUMIDITY_VALUE
   * @generated
   * @ordered
   */
  HUMIDITY(2, "humidity", "humidity"),

  /**
   * The '<em><b>Wind</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WIND_VALUE
   * @generated
   * @ordered
   */
  WIND(3, "wind", "wind"),

  /**
   * The '<em><b>Rain</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RAIN_VALUE
   * @generated
   * @ordered
   */
  RAIN(4, "rain", "rain");

  /**
   * The '<em><b>Hydro</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HYDRO
   * @model name="hydro" literal="idro_level"
   * @generated
   * @ordered
   */
  public static final int HYDRO_VALUE = 0;

  /**
   * The '<em><b>Temperature</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TEMPERATURE
   * @model name="temperature" literal="temp"
   * @generated
   * @ordered
   */
  public static final int TEMPERATURE_VALUE = 1;

  /**
   * The '<em><b>Humidity</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HUMIDITY
   * @model name="humidity"
   * @generated
   * @ordered
   */
  public static final int HUMIDITY_VALUE = 2;

  /**
   * The '<em><b>Wind</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WIND
   * @model name="wind"
   * @generated
   * @ordered
   */
  public static final int WIND_VALUE = 3;

  /**
   * The '<em><b>Rain</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RAIN
   * @model name="rain"
   * @generated
   * @ordered
   */
  public static final int RAIN_VALUE = 4;

  /**
   * An array of all the '<em><b>TYPES</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TYPES[] VALUES_ARRAY =
    new TYPES[]
    {
      HYDRO,
      TEMPERATURE,
      HUMIDITY,
      WIND,
      RAIN,
    };

  /**
   * A public read-only list of all the '<em><b>TYPES</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TYPES> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>TYPES</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TYPES get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TYPES result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>TYPES</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TYPES getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TYPES result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>TYPES</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TYPES get(int value)
  {
    switch (value)
    {
      case HYDRO_VALUE: return HYDRO;
      case TEMPERATURE_VALUE: return TEMPERATURE;
      case HUMIDITY_VALUE: return HUMIDITY;
      case WIND_VALUE: return WIND;
      case RAIN_VALUE: return RAIN;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TYPES(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TYPES
