/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SensorDSLUiModule extends AbstractSensorDSLUiModule {

	public SensorDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
