/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SensorDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSensorDSLWebModule extends DefaultWebModule {

}
