/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.tests

import com.google.inject.Inject
import it.unibo.sensor.dsl.sensorDSL.SensorDefinition
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(SensorDSLInjectorProvider)
class SensorDSLParsingTest {
	@Inject
	ParseHelper<SensorDefinition> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
