/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.ui.tests;

import com.google.inject.Injector;
import it.unibo.sensor.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SensorDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("it.unibo.sensor.dsl.SensorDSL");
	}

}
