/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.parser.antlr;

import com.google.inject.Inject;
import it.unibo.sensor.dsl.parser.antlr.internal.InternalSensorDSLParser;
import it.unibo.sensor.dsl.services.SensorDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SensorDSLParser extends AbstractAntlrParser {

	@Inject
	private SensorDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSensorDSLParser createParser(XtextTokenStream stream) {
		return new InternalSensorDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SensorDefinition";
	}

	public SensorDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SensorDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
