/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SensorDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/unibo/sensor/dsl/parser/antlr/internal/InternalSensorDSL.tokens");
	}
}
