/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unibo.sensor.dsl.SensorDSLRuntimeModule;
import it.unibo.sensor.dsl.SensorDSLStandaloneSetup;
import it.unibo.sensor.dsl.ide.SensorDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class SensorDSLWebSetup extends SensorDSLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SensorDSLRuntimeModule(), new SensorDSLIdeModule(), new SensorDSLWebModule()));
	}
	
}
