/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SensorDSLWebModule extends AbstractSensorDSLWebModule {
}
