/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.serializer;

import com.google.inject.Inject;
import it.unibo.sensor.dsl.services.SensorDSLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SensorDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SensorDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_GeneralCronjobInfo_HoursKeyword_1_1_2_0_or_MinutesKeyword_1_1_2_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SensorDSLGrammarAccess) access;
		match_GeneralCronjobInfo_HoursKeyword_1_1_2_0_or_MinutesKeyword_1_1_2_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getGeneralCronjobInfoAccess().getHoursKeyword_1_1_2_0()), new TokenAlias(false, false, grammarAccess.getGeneralCronjobInfoAccess().getMinutesKeyword_1_1_2_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_GeneralCronjobInfo_HoursKeyword_1_1_2_0_or_MinutesKeyword_1_1_2_1.equals(syntax))
				emit_GeneralCronjobInfo_HoursKeyword_1_1_2_0_or_MinutesKeyword_1_1_2_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'hours' | 'minutes'
	 *
	 * This ambiguous syntax occurs at:
	 *     value=INT (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_GeneralCronjobInfo_HoursKeyword_1_1_2_0_or_MinutesKeyword_1_1_2_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
