/*
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSensorDSLScopeProvider extends DelegatingScopeProvider {
}
