/**
 * generated by Xtext 2.37.0
 */
package it.unibo.sensor.dsl.sensorDSL.impl;

import it.unibo.sensor.dsl.sensorDSL.GeneralGatewayInfo;
import it.unibo.sensor.dsl.sensorDSL.SensorDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>General Gateway Info</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl#getUrl <em>Url</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl#getPort <em>Port</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl#getRegister <em>Register</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl#getShutdown <em>Shutdown</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl#getDetection <em>Detection</em>}</li>
 *   <li>{@link it.unibo.sensor.dsl.sensorDSL.impl.GeneralGatewayInfoImpl#getAlert <em>Alert</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GeneralGatewayInfoImpl extends MinimalEObjectImpl.Container implements GeneralGatewayInfo
{
  /**
   * The default value of the '{@link #getUrl() <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUrl()
   * @generated
   * @ordered
   */
  protected static final String URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUrl() <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUrl()
   * @generated
   * @ordered
   */
  protected String url = URL_EDEFAULT;

  /**
   * The default value of the '{@link #getPort() <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPort()
   * @generated
   * @ordered
   */
  protected static final int PORT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPort() <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPort()
   * @generated
   * @ordered
   */
  protected int port = PORT_EDEFAULT;

  /**
   * The default value of the '{@link #getRegister() <em>Register</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegister()
   * @generated
   * @ordered
   */
  protected static final String REGISTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRegister() <em>Register</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegister()
   * @generated
   * @ordered
   */
  protected String register = REGISTER_EDEFAULT;

  /**
   * The default value of the '{@link #getShutdown() <em>Shutdown</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShutdown()
   * @generated
   * @ordered
   */
  protected static final String SHUTDOWN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShutdown() <em>Shutdown</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShutdown()
   * @generated
   * @ordered
   */
  protected String shutdown = SHUTDOWN_EDEFAULT;

  /**
   * The default value of the '{@link #getDetection() <em>Detection</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDetection()
   * @generated
   * @ordered
   */
  protected static final String DETECTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDetection() <em>Detection</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDetection()
   * @generated
   * @ordered
   */
  protected String detection = DETECTION_EDEFAULT;

  /**
   * The default value of the '{@link #getAlert() <em>Alert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlert()
   * @generated
   * @ordered
   */
  protected static final String ALERT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAlert() <em>Alert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlert()
   * @generated
   * @ordered
   */
  protected String alert = ALERT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeneralGatewayInfoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SensorDSLPackage.Literals.GENERAL_GATEWAY_INFO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUrl()
  {
    return url;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUrl(String newUrl)
  {
    String oldUrl = url;
    url = newUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SensorDSLPackage.GENERAL_GATEWAY_INFO__URL, oldUrl, url));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPort()
  {
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPort(int newPort)
  {
    int oldPort = port;
    port = newPort;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SensorDSLPackage.GENERAL_GATEWAY_INFO__PORT, oldPort, port));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRegister()
  {
    return register;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRegister(String newRegister)
  {
    String oldRegister = register;
    register = newRegister;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SensorDSLPackage.GENERAL_GATEWAY_INFO__REGISTER, oldRegister, register));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getShutdown()
  {
    return shutdown;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShutdown(String newShutdown)
  {
    String oldShutdown = shutdown;
    shutdown = newShutdown;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SensorDSLPackage.GENERAL_GATEWAY_INFO__SHUTDOWN, oldShutdown, shutdown));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDetection()
  {
    return detection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDetection(String newDetection)
  {
    String oldDetection = detection;
    detection = newDetection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SensorDSLPackage.GENERAL_GATEWAY_INFO__DETECTION, oldDetection, detection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAlert()
  {
    return alert;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlert(String newAlert)
  {
    String oldAlert = alert;
    alert = newAlert;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SensorDSLPackage.GENERAL_GATEWAY_INFO__ALERT, oldAlert, alert));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__URL:
        return getUrl();
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__PORT:
        return getPort();
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__REGISTER:
        return getRegister();
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__SHUTDOWN:
        return getShutdown();
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__DETECTION:
        return getDetection();
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__ALERT:
        return getAlert();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__URL:
        setUrl((String)newValue);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__PORT:
        setPort((Integer)newValue);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__REGISTER:
        setRegister((String)newValue);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__SHUTDOWN:
        setShutdown((String)newValue);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__DETECTION:
        setDetection((String)newValue);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__ALERT:
        setAlert((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__URL:
        setUrl(URL_EDEFAULT);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__PORT:
        setPort(PORT_EDEFAULT);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__REGISTER:
        setRegister(REGISTER_EDEFAULT);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__SHUTDOWN:
        setShutdown(SHUTDOWN_EDEFAULT);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__DETECTION:
        setDetection(DETECTION_EDEFAULT);
        return;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__ALERT:
        setAlert(ALERT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__URL:
        return URL_EDEFAULT == null ? url != null : !URL_EDEFAULT.equals(url);
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__PORT:
        return port != PORT_EDEFAULT;
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__REGISTER:
        return REGISTER_EDEFAULT == null ? register != null : !REGISTER_EDEFAULT.equals(register);
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__SHUTDOWN:
        return SHUTDOWN_EDEFAULT == null ? shutdown != null : !SHUTDOWN_EDEFAULT.equals(shutdown);
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__DETECTION:
        return DETECTION_EDEFAULT == null ? detection != null : !DETECTION_EDEFAULT.equals(detection);
      case SensorDSLPackage.GENERAL_GATEWAY_INFO__ALERT:
        return ALERT_EDEFAULT == null ? alert != null : !ALERT_EDEFAULT.equals(alert);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (url: ");
    result.append(url);
    result.append(", port: ");
    result.append(port);
    result.append(", register: ");
    result.append(register);
    result.append(", shutdown: ");
    result.append(shutdown);
    result.append(", detection: ");
    result.append(detection);
    result.append(", alert: ");
    result.append(alert);
    result.append(')');
    return result.toString();
  }

} //GeneralGatewayInfoImpl
